#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "tkb-wasm"
version = "0.1.0"
authors = ["Amit Kumar <kamit17@outlook.com>"]
description = "My First Wasm App"

[[trigger.http]]
route = "/tkb"
component = "tkb-wasm"

[component.tkb-wasm]
source = "tkb_wasm.wasm"
allowed_outbound_hosts = []
[component.tkb-wasm.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
